version: '3.8'

services:
  # 1. SERVIÇO DE BACKEND (API)
  api:
    build:
      context: ./apps/api  # Onde o Dockerfile da API está
    ports:
      - "3000:3000"         # Expõe a porta 3000 da máquina para a porta 3000 do container
    container_name: catgen-api
    restart: always
    environment:
      # Variáveis de ambiente da API (se precisássemos de chaves, estariam aqui)
      - NODE_ENV=production

  # 2. SERVIÇO DE FRONTEND (PWA)
  web:
    build:
      context: ./apps/web  # Onde o Dockerfile do PWA está
    ports:
      - "8080:80"         # Expõe a porta 8080 da máquina para a porta 80 do Nginx
    container_name: catgen-web
    restart: always
    # Garante que o frontend só inicie depois que o backend estiver de pé
    depends_on:
      - api
    environment:
      # Variáveis para o Frontend (Opcional no nosso caso, já que usamos 'localhost:3000' diretamente no JS)
      - VITE_API_URL=http://api:3000 
      # Embora tenhamos usado localhost no app.js, dentro do docker-compose
      # o nome do serviço 'api' resolve para o IP do container do backend.